---
abstract: 'promote Perl primitives (hashes, scalars, arrays, and filehandles), either tie()d or not, to become hybrid objects'
author:
  - 'Alexandr Kononoff (L<mailto:parsels@mail.ru>)'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Object-Hybrid
provides:
  Class::Tag:
    file: lib/Object/Hybrid.pm
    version: 0
  Object::Hybrid:
    file: lib/Object/Hybrid.pm
    version: 0.03_03
  Object::Hybrid::ARRAY:
    file: lib/Object/Hybrid.pm
    version: 0
  Object::Hybrid::CLASS:
    file: lib/Object/Hybrid.pm
    version: 0
  Object::Hybrid::Class:
    file: lib/Object/Hybrid.pm
    version: 0
  Object::Hybrid::GLOB:
    file: lib/Object/Hybrid.pm
    version: 0
  Object::Hybrid::HASH:
    file: lib/Object/Hybrid.pm
    version: 0
  Object::Hybrid::SCALAR:
    file: lib/Object/Hybrid.pm
    version: 0
requires:
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.03_03
