---
abstract: 'promote Perl primitives (hashes, scalars, arrays, and filehandles), either tie()d or not, to become hybrid objects'
author:
  - 'Alexandr Kononoff (L<mailto:parsels@mail.ru>)'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3601'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Object-Hybrid
provides:
  Class::Tag:
    file: lib/Class/Tag.pm
    version: 0.09
  Object::Hybrid:
    file: lib/Object/Hybrid.pm
    version: 0.07
  Object::Hybrid::ARRAY:
    file: lib/Object/Hybrid.pm
    version: 0
  Object::Hybrid::BASE:
    file: lib/Object/Hybrid.pm
  Object::Hybrid::Class:
    file: lib/Object/Hybrid.pm
    version: 0
  Object::Hybrid::GLOB:
    file: lib/Object/Hybrid.pm
    version: 0
  Object::Hybrid::HASH:
    file: lib/Object/Hybrid.pm
    version: 0
  Object::Hybrid::SCALAR:
    file: lib/Object/Hybrid.pm
    version: 0
  PACKAGE_REPLACE:
    file: lib/Object/Hybrid.pm
requires:
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.07
